Matched object and matchMz TargetMass2MzParam
michaelwitting/MetaboAnnotation pull request #11
Opened 2021-04-21 16:40 UTC by andreavicini

2021-04-21 18:13 UTC, michaelwitting commented
Looks good to me. One general question from my side would be: Can we have a `@param` slot in the `Matched`? This could be by default `NA`, but the different methods can add the parameter object for the matching. This would also allow us to identify at a later stage which kind of matching was performed, e.g. if specific further methods for downstream processing of results shall be generated.

2021-04-22 07:03 UTC, jorainer commented
I'll have a look at this later today/early tomorrow. Regarding the `@param` slot @michaelwitting, we have a `@metadata` slot where we could add anything we want.  I would like to keep it that way, because having an `@param` slot would imply/require that this type of object is added or available, but I would like to keep that object as generic as possible to allow its reuse also in other situations.

2021-04-22 07:13 UTC, michaelwitting commented
No problem, I overlooked the `@metadata` slot.

2021-04-23 06:27 UTC, jorainer requested changes
Thanks @andreavicini ! Looks good what you have implemented, but I would suggest some improvements/changes in the `Matched` class to (better) support `@query` and `@target` without dimensions.

2021-04-23 06:27 UTC, jorainer commented on R/Matched.R
> +
I think it might be helpful to have a helper function `.extract_elements` that can be used instead of `[` on `@query` and `@target`. That way you would not have to bother whether query or target is a vector or a two-dimensional thing. it could be implemented like:

```r
.extract_elements <- function(x, i, j) {
    if (length(dim(x))) x[i, j]
    else x[i]
}
```

2021-04-23 06:27 UTC, jorainer commented on R/Matched.R
> +    if(is.data.frame(target(x)))  cnt <- paste0("target_", colnames(target(x)))
Also, if `@query` or `@target` has only a single dimension you should return `"query"` and/or `"target"` as the *column* name. Because in that case we should support for example `x$target` to extract the elements of `@target` (even if target is only a `list` or a vector). Same for `@query`.

2021-04-23 06:27 UTC, jorainer commented on R/Matched.R
> +data <- function(object, columns = colnames(object)){
I did not check, but this should also support the case where `@query` and/or `@target` are dimensionless (`list` or `vector` or similar). In that case they should be reported as column `"query"` or `"target"` in the resulting `DataFrame`.

2021-04-23 06:27 UTC, jorainer commented on R/Matched.R
> +    if(is.null(dim(x@query))) slot(x, "query", check = FALSE) <- x@query[i]
here you could then use for example the `.extract_elements` function that I suggested below.

2021-04-23 06:27 UTC, jorainer commented on R/matchMz.R
> +# Should I add also adducts to this class?
yep, please add also a slot `adduct`.

2021-04-23 06:27 UTC, jorainer commented on R/matchMz.R
> +          function(query, target, param, adducts = c("[M+H]+")){
`adduct` should be a slot of `param` hence it's not needed to add as a parameter here. I would however suggest to add a parameter `BPPARAM = SerialParam()` to optionally enable parallel processing.

2021-04-23 06:27 UTC, jorainer commented on R/matchMz.R
> +            matches <- do.call(rbind, lapply(seq_along(mz), .getMatches, mz,
and here use `bplapply` instead of `lapply` and pass also `BPPARAM = BPPARAM` as (the last) parameter to that call.

2021-04-23 06:27 UTC, jorainer commented on R/matchMz.R
> +#' @author
please add yourself as author - I would also suggest that you add yourself as an author to internal functions (even if you use then `@noRd` there to avoid generation of a documentation) - just to know who we have to blame if the function is not working ;)

2021-05-05 06:23 UTC, jorainer requested changes
Great PR @andreavicini ! I have some few minor points but then I'm looking forward merging this and testing it thoroughly.

2021-05-05 06:23 UTC, jorainer commented on R/Matched.R
>              vals <- do.call("$", list(x@target[x@matches$target_idx, ],
I would suggest to change this to a simple `vals <- x@target[x@matches$target_idx, sub("target_", "", name)]` since this is for two-dimensional *target* (`matrix`, `data.frame`, etc) and they should have two dimensions. The `$` would only work if target is a `data.frame` but would fail if it is a `matrix`.

2021-05-05 06:23 UTC, jorainer commented on R/Matched.R
>              vals <- do.call("$", list(x@target[x@matches$target_idx, ],
Note: that's also true for the `do.call("$", list(x@query, name))[idxs]`.

2021-05-05 06:23 UTC, jorainer commented on R/Matched.R
> +        # corresponding element. Is that acceptable or should I set it to NA here?
good point. If we return `NA` in all other cases (e.g. if `target` or `query` is a `numeric` or `data.frame`) I would also suggest to return an `NA` here.

2021-05-05 06:23 UTC, jorainer commented on R/Matched.R
> +    # we decided to use "query" and "target" to extract query and target objects.
Good point again. But I would maybe add that to the `setValidity` for `Matched` above, i.e. check there that `@matches` does not have columns named `"query"` or `"target"`. That way we have all the validity checks in one place and not distributed across the code.

2021-05-06 11:38 UTC, jorainer approved these changes
Looks good to me! I will merge and test locally.

2021-05-06 11:38 UTC, merged